language: node_js  #设置语言

node_js: 12.18.3  #设置相应的版本

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

before_install:
    - export TZ='Asia/Shanghai' # 更改时区

install:
  - npm install hexo-cli -g #安装hexo及插件
  - npm install hexo-deployer-git --save
  - npm install hexo-renderer-pug hexo-renderer-stylus --save
  - npm install --save hexo-helper-live2d
  - npm install live2d-widget-model-shizuku
  - npm install hexo-douban
  - npm install hexo-wordcount --save
  - npm install --save hexo-filter-flowchart
  - npm install hexo-generator-search --save
  - npm install hexo-generator-sitemap --save
  - npm install --save hexo-submit-urls-to-search-engine
  - npm install hexo-generator-feed --save


script:
  - hexo clean  #清除
  - hexo g   #生成
  - hexo douban -bgm #生成豆瓣页面
after_script:
    - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
    - cd .deploy_git
    - git checkout master
    - cd ../
    - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
    - cd ./public
    - git config user.name "Travis"  #修改name
    - git config user.email "zhouzishun@mail.zzshub.cn"  #修改email
    - git add .
    - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
    - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master  #Travis_Token是在Travis中配置环境变量的名称

branches:
  only:
    - source  #只监测master分支，master是我的分支的名称，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/ZzzzzzS/ZzzzzzS.github.io.git  #设置GH_REF，注意更改yourname

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - zhouzishun@mail.zzshub.cn
  on_success: always
  on_failure: always
